---
- name: "Pick appropriate groups for localhost"
  hosts: localhost
  connection: local
  tasks:
    - import_tasks: tasks/localhost-group-placement.yml
  tags: always

- name: "Rename instances"
  hosts: localhost
  connection: local
  tasks:
    - name: re-name old instances
      amazon.aws.ec2_instance:
        profile: fedora-copr
        instance_ids: "{{ item.old_instance_id }}"
        name: "{{ item.name  }}-{{ copr_instance }}-old"
        purge_tags: false
        tags:
          CoprFedoraNextWorkflow: old
        termination_protection: false
      with_items:
        - "{{ backend }}"
        - "{{ frontend }}"
        - "{{ keygen }}"
        - "{{ distgit }}"

    - name: re-name new instances
      amazon.aws.ec2_instance:
        profile: fedora-copr
        instance_ids: "{{ item.new_instance_id }}"
        name: "{{ item.name  }}-{{ copr_instance }}"
        purge_tags: false
        tags:
          CoprFedoraNextWorkflow: new
        termination_protection: true
      with_items:
        - "{{ backend }}"
        - "{{ frontend }}"
        - "{{ keygen }}"
        - "{{ distgit }}"
